/* Generated by Opal 0.9.2 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var OPAL_CONFIG = { method_missing: true, arity_check: false, freezing: true, tainting: true };
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, project_type = nil, http_path = nil, css_dir = nil, sass_dir = nil, images_dir = nil, javascripts_dir = nil, fonts_dir = nil;

  Opal.add_stubs(['$require']);
  self.$require("compass/import-once/activate");
  project_type = "stand_alone";
  http_path = "/";
  css_dir = "_site/stylesheets";
  sass_dir = "stylesheets";
  images_dir = "images";
  javascripts_dir = "javascripts";
  return fonts_dir = "fonts";
})(Opal);
