// vim: set syntax=asciidoc:

// Start of document parameters

:toc: macro
:icons: font
:awestruct-layout: asciidoctor

// End of document parameters


== Contributor Roles


toc::[levels=2]


There are multiple ways community members can contribute to the OpenIndiana Documentation revitalization effort.
These contributions fall into several different roles:


=== Content Creator

The easiest way to help the docs revitalization effort is by writing content.
The content creator would (as the title suggests) develop content to be hosted on the docs website.
Content could include just about anything, news posts, tutorials, Howto's, or larger efforts such as the handbook or updating the OSOL books.

The nice thing about helping with content creation is the level of commitment is entirely up to the individual.
In other words, there is no requirement to get involved in anything major.
In contrast, it would probably be better to start small and only later consider taking on something larger.
Required skills would include a willingness to write, and a willingness to work with content reviewers.


=== Content Reviewer

The content reviewer would effectively perform the role of editorial reviewer.
This person would review pull request and provide editorial feedback to content creators.
This role would also engage with the website developer to help place content appropriately as well as assist the website developer with site organization.
Helpful skills would include good organization and people skills as well as a knack for performing editorial reviews.


=== Website Developer

The docs website developer would work with content creators and content reviewers helping to improve site functionality and organization.
This role requires front end web development skills and would be working directly with the Awestruct framework.
Helpful skills would include experience with Ruby, HAML, HTML, and CSS.
The website developer would also be working with Awestruct extensions and helpers which may also include working directly with the Awestruct API.



