// vim: set syntax=asciidoc:

// Start of document parameters

:toc: macro
:icons: font
:awestruct-layout: asciidoctor

// End of document parameters



// Start of TODO
//
// Write a table where _included_ features of OpenIndiana are compared to _licensed_ features found in commercial software.
// - For example: Qemu-KVM | HyperV, Esxi, etc. , Zones | Docker, etc.
//
// Need to look at the legal aspects of mentioning trademarked names within documentation (to help keep openindiana out of trouble).
// - Also need to look at document licensing, whether to put licenses in the docs, etc.
//
// Have a look at the "Newbie FAQ" from hub.opensolaris.org
// - See: http://web.archive.org/web/20100111014254/http://hub.opensolaris.org/bin/view/Community+Group+documentation/newbie_faq
//
// Add a blurb about switching to hipster. Link to :http://wiki.openindiana.org/oi/Hipster#Hipster-switching
// - Link in download URL's for ISO's, etc.: See release notes:http://wiki.openindiana.org/oi/2016.04+Release+notes
//
// End of TODO



== The OpenIndiana FAQ


toc::[levels=2]


=== What is OpenIndiana?

The OpenIndiana project is the open source community which develops, maintains, and supports the https://en.wikipedia.org/wiki/OpenIndiana[OpenIndiana] distribution, an https://en.wikipedia.org/wiki/Illumos[illumos] based Unix-like operating system derived from OpenSolaris.
The purpose of the OpenIndiana Project is to ensure the continued availability of an openly developed distribution based on OpenSolaris.
The OpenIndiana project is also a continuation of the collaborative effort and community spirit of the https://en.wikipedia.org/wiki/OpenSolaris[OpenSolaris project].

For a comprehensive history of the OpenSolaris project, see Jim Grisanzio's https://jimgrisanzio.wordpress.com/opensolaris/[OpenSolaris timeline].

=== Why is it called OpenIndiana?

OpenIndiana obtains its name from Project Indiana, an open source effort by Sun Microsystems (now Oracle Corporation) to produce OpenSolaris, a community developed Unix-like distribution based on Sun Solaris.
Project Indiana was led by Ian Murdock, founder of the Debian Linux Distribution.


=== How are OpenIndiana and illumos related?

The https://illumos.org[illumos project] is the open source community which develops, maintains, and supports  https://github.com/illumos/illumos-gate[illumos-gate], the core software used by the OpenIndiana distribution.
Similar to a BSD `src` tree, illumos-gate includes the illumos kernel, along with many of the device drivers, core libraries, and system utilities.

To form a complete distribution, the OpenIndiana project combines illumos-gate with oi-userland, and with other free and open-source software.
This melding of software from many different open-source projects is similar to how Linux distributions use the Linux kernel along with software from the GNU and various other open source projects. 


=== How does OpenIndiana differ from OpenSolaris?

Some of the differences between OpenIndiana and OpenSolaris can be characterized as follows:

* Sun/Oracle's proprietary OS/NET consolidation has been replaced with https://github.com/OpenIndiana/illumos-gate[illumos-gate].
* Many of the original OpenSolaris software consolidations have been reorganized into a single https://github.com/OpenIndiana/oi-userland[oi-userland] consolidation.
* Oracle's Sun Studio has been replaced with the open source GNU GCC compiler.
* XVM (XEN) has been replaced with the illumos-kvm port.

[NOTE]
OpenIndiana Hipster's transition from Sun Studio to GCC has resulted in a discontinuance of ABI (binary) compatibility with previous releases of OpenIndiana, Oracle Solaris, and OpenSolaris.
Applications coded in the `C` language should continue to work normally.
Therefore, this change only affects applications written in the `C++` language.

=== How does OpenIndiana compare to BSD or Linux?


// TODO
// Write a table providing a matrix comparing commands between BSD/Linux/OpenIndiana.
// See: https://wiki-bsse.ethz.ch/display/ITDOC/Major+difference+between+Linux+and+Solaris
// Also can look at old OpenSolaris website for ideas, suggestions, etc.


All of these operating systems follow the Unix paradigm and contain tools and commands which bear a similar resemblance, although specific feature sets and command usage may be dissimilar.
If you are coming to OpenIndiana from either BSD or Linux, you will quickly learn these differences.
In no time at all, you'll feel right at home working with OpenIndiana's tools and commands.


=== What features does OpenIndiana have?

OpenIndiana contains the following enterprise class features and more:

[cols="1,2"]
|===
|Feature |Description

| ZFS
| https://en.wikipedia.org/wiki/ZFS[ZFS File System and Volume Manager]

| DTrace
| https://en.wikipedia.org/wiki/DTrace[Dynamic Tracing Framework - (System Introspection)]

| Crossbow
| https://en.wikipedia.org/wiki/OpenSolaris_Network_Virtualization_and_Resource_Control[Network Virtualization and Resource Control]

| SMF
| http://illumos.org/man/5/smf[Service Management Facility]

| FMA
| http://illumos.org/man/1M/fmd[Fault Management Architecture]

| COMSTAR
| http://illumos.org/man/1m/itadm[Common Multiprotocol SCSI TARget - (ISCSI Target Framework)]

| KVM
| https://en.wikipedia.org/wiki/Kernel-based_Virtual_Machine[Kernel Virtual Machine - (Operating System Virtualization)]

| Zones
| https://en.wikipedia.org/wiki/Solaris_Containers[OS Level Virtualized Application Containers]

| Time-Slider
| http://www.serverwatch.com/tutorials/article.php/3831881/Say-Cheese-OpenSolaris-Time-Slider.htm[Automated ZFS Snapshots and Rollbacks]

| RBAC
| http://www.c0t0d0s0.org/archives/4073-Less-known-Solaris-features-RBAC-and-Privileges-Part-1-Introduction.html[Role-Based Access Control]

| IPMP
| http://www.c0t0d0s0.org/archives/6292-Less-known-Solaris-features-IP-Multipathing-Part-1-Introduction.html[IP Network Multipathing]

| DLMP
| http://www.c0t0d0s0.org/archives/7553-Less-known-Solaris-Features-Data-Link-Multipathing.html[Data Link Multipathing]

|===


=== What is the OpenIndiana release schedule?

Approximately every six months, the OpenIndiana project releases a snapshot of the Hipster rolling release branch.
Ideally suited for both workstations and servers, simply choose the installer type which best serves your needs.

|===
| Workstation | Server

| Live installer (Gnome desktop) | Text installer (command line console)
|===

For more information, see: <<Where can I download OpenIndiana Hipster?>>::

[NOTE]
====
* OpenIndiana releases from the legacy oi-dev-151x branch are no longer maintained.
* For those desiring to upgrade from legacy installations, Hipster IPS repositories are available.
* While upgrades from the legacy branch are possible, the most trouble free method is to perform a clean install.
====

[CAUTION]
====
Hipster is a rapid development branch where software versions are frequently updated.
While every package is tested to ensure stability, caution is nevertheless warranted when deploying Hipster into mission critical production environments.
====

=== What are the recommended hardware specifications?

|===
| CPU | Disk Space | Memory (RAM)

| 64 Bit | 20GB (or more) | 4GB (or more)
|===


=== Does OpenIndiana support internationalization and localization?

Yes, when installing OpenIndiana, you may choose from 47 different keyboard layouts and 22 different languages.


=== Does OpenIndiana provide security and bug fixes?

Yes, absolutely.
For the actively maintained Hipster rolling release, the OpenIndiana project seeks to ensure all known flaws are quickly mitigated.
For this effort to succeed, we ask our user base to diligently bring security and bugfix concerns to our attention by submitting a ticket with the https://www.illumos.org/projects/openindiana/issues[OpenIndiana Bug Tracker].


=== Where can I download OpenIndiana Hipster?


|===
| OpenIndiana Hipster Download Mirrors

| http://dlc.openindiana.org/isos/hipster[Primary Mirror] 
| http://ftp.vim.org/os/openindiana.org/dlc/isos/hipster[Vim.org Alternate Mirror]
| http://dlc.openindiana.org/torrents/[Torrents]
|===


[NOTE]
====
For the 201604 release, http://distrowatch.com/weekly.php?issue=20160425#torrent[Distrowatch] has kindly hosted a https://torrent.resonatingmedia.com/torrents/OI-hipster-gui-20160421.iso.b913f8d70cbd57e3.torrent[torrent] of the OI-hipster-gui-20160421.iso.
The MD5 checksum for this torrent is: *e9a748169a4d1898ba140c636b72ea59*

If you wish to purchase a ready made DVD or USB drive there is also https://www.osdisc.com/products/solaris/openindiana[OSDISC.COM].
====


[IMPORTANT]
====
* OpenIndiana Hipster does not yet support USB 3.0 devices.
** Effectively this means it is not yet possible to install the operating system from a USB 3.0 device.
** When when attaching USB 2.0 devices to your system, please ensure they are *NOT* attached to a USB 3.0 port.
====

[WARNING]
====
* There are 2 unique USB header files (1G and 2G).
* When creating a bootable flash drive, please ensure you have selected the correct file.
** The 1G.header is only suitable for use with the text installer (Command line console).
** The 2G.header is only suitable for use with the live installer (Gnome desktop).
** The files are *NOT* interchangeable.
====

=== What package manager does OpenIndiana use?

OpenIndiana uses the network based https://en.wikipedia.org/wiki/Image_Packaging_System[Image Packaging System (IPS)].
For those coming to OpenIndiana from BSD or Linux, the IPS package manager will be an easy transition.
You may also continue to use the legacy `pkgadd/pkgrm` commands.

[NOTE]
The OpenIndiana distribution provides a basic set of packages, along with some extras.
There are also 3rd party repositories which provide additional packages.
If you wish to contribute by helping to expand package availability, please read further down about how to get involved with the OpenIndiana project.

The following IPS repositories are available:

[cols="1,2,2"]
|===
| Repository Name | Repository URL | Description

| openindiana.org
| http://pkg.openindiana.org/hipster
| Hipster primary package repository

| hipster-encumbered
| http://pkg.openindiana.org/hipster-encumbered
| Hipster encumbered license packages

| localhostoih
| http://sfe.opencsw.org/localhostoih
| 3rd party http://sfe.opencsw.org[Spec Files Extra (SFE)] packages
|===

[NOTE]
====
To add a new publisher: `pkg set-publisher -g repository_url repository_name`

To change an existing publisher: `pkg set-publisher -G http://pkg.openindiana.org/hipster-2015 -g http://pkg.openindiana.org/hipster openindiana.org`

For further information consult the http://www.linuxtopia.org/online_books/opensolaris_2008/IMGPACKAGESYS/html/docinfo.html[OpenSolaris Image Packaging System Guide] as well as the pkg(1) man page included with OpenIndiana Hipster.
====

=== What books are available to help with learning OpenIndiana?

There are several resources which will assist you with learning to use OpenIndiana.
While somewhat dated now, these resources are largely still relevant.

* http://www.bookfinder.com/search/?keywords=1430218916&new=&used=&ebooks=&classic=&lang=en&st=sh&ac=qr&submit=[Pro OpenSolaris]
** A gentle and well written introduction to OpenSolaris. It weighs in at 250 pages.

* http://www.bookfinder.com/search/?keywords=0470385480&new=&used=&ebooks=&classic=&lang=en&st=sh&ac=qr&submit=[OpenSolaris Bible]
** A much larger and more comprehensive reference book of nearly 1000 Pages.

* https://illumos.org/books/[The illumos bookshelf]
** Updated for illumos, the illumos bookshelf consists of several original OpenSolaris advanced administration and development titles.

* http://www.linuxtopia.org/online_books/opensolaris_2008/index.html[OpenSolaris 2008 Docs]
** Originally released by the OpenSolaris project, this collection consists of over 40 titles ranging from development to systems administration.

[NOTE]
In late 2009, the OpenSolaris project released a newer version of the OpenSolaris book collection.
An effort currently exists within the OpenIndiana community to revise and condense these titles into a more streamlined collection which more closely follows the development state of OpenIndiana Hipster.
The documentation team is also working to produce an updated OpenIndiana handbook as well as task based tutorials.
If you wish to participate in this effort, please indicate your interest via the IRC channels or the mailing lists. 


=== How do I get involved with the OpenIndiana Project?

As a community supported open source software project, the success and future of OpenIndiana depends entirely on you.
While the most important thing is to download and begin using OpenIndiana, there are many different ways to contribute.
Tell your friends and coworkers about OpenIndiana as well, and don't forget to report all issues to our bug tracker.

Below is a list of OpenIndiana community resources you may find helpful:

|===
| Resource | URL

| User Support IRC channel
| irc://irc.freenode.net/openindiana[#openindiana on irc.freenode.net]

| Development IRC channel
| irc://irc.freenode.net/oi-dev[#oi-dev on irc.freenode.net]

| Documentation IRC channel
| irc://irc.freenode.net/oi-documentation[#oi-documentation on irc.freenode.net]

| OpenIndiana Mailing Lists
| http://openindiana.org/mailman

| OpenIndiana Wiki
| http://wiki.openindiana.org

| OpenIndiana Bug Tracker
| http://www.illumos.org/projects/openindiana/issues
|===

Here are just some of the many ways you may contribute:

* Artwork
* Development
* Documentation - Handbook, Tutorials, News articles, etc.
* Evangelism - blogging about OpenIndiana, attending conferences, etc.
* Packaging - oi-userland, 3rd party packaging (SFE, etc.)
* Release engineering
* Translation
* Utilities maintenance
* Website Maintenance

Just ask on the IRC channels or mailing lists about how you may contribute.

For additional details, including links to our GitHub source repositories, please see: http://www.openindiana.org/community/getting-involved


=== Does OpenIndiana provide a SPARC release?

OpenIndiana Hipster is not currently available for the SPARC platform.

In regards to the creation of a SPARC port of OpenIndiana Hipster, there have been periodic discussions on the http://openindiana.org/mailman/listinfo[OpenIndiana mailing lists].
If you would like to see SPARC become a supported platform, please help us by joining the http://www.openindiana.org/community/getting-involved[OpenIndiana community].

.Historical SPARC releases
In 2009, the OpenSolaris project released an http://dlc.openindiana.org/isos/opensolaris[OpenSolaris text install ISO], and much more recently, there was work done by Adam Glasgall who produced an http://neutron-star.mit.edu/OpenIndiana_Text_SPARC.iso[unofficial SPARC text install ISO] based on oi-dev-151-a8. 

.illumos distributions with SPARC releases
The following illumos based distributions are known to support the SPARC platform:

* http://www.dilos.org/download[Dilos]
* http://opensxce.org[OpenSCXE]
* http://www.tribblix.org/download.html[Tribblix]

.Commercial distributions with SPARC releases
For production use on modern SPARC hardware, there is also commercial https://www.oracle.com/solaris/solaris11/index.html[Oracle Solaris].


=== What are the licensing terms for OpenIndiana?

OpenIndiana is composed of software from multiple different sources, each with its own licensing terms. 

Here is a list of the most commonly used licenses:

* https://opensource.org/licenses/CDDL-1.0[Common Development and Distribution License (CDDL-1.0)]
* http://illumos.org/license/PDL[PUBLIC DOCUMENTATION LICENSE (PDL), Version 1.01]
* https://opensource.org/licenses/MIT[The MIT License (MIT)]
* https://opensource.org/licenses/BSD-2-Clause[The BSD 2-Clause License]
* http://www.gnu.org/licenses/licenses.en.html[GNU licenses]
